services:
  proxy:
    image: ghcr.io/wbmentertainment/nginx:latest
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/wbm/projects/media-nginx/NAS/html:/var/www/html
      - /home/wbm/projects/media-nginx/NAS/certbot/conf:/etc/letsencrypt
      - /home/wbm/projects/media-nginx/NAS/certbot/www:/var/www/certbot
    networks:
      - nginx-net
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /home/wbm/projects/media-nginx/NAS/certbot/conf:/etc/letsencrypt
      - /home/wbm/projects/media-nginx/NAS/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: >
      "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"
      
networks:
  nginx-net:
    name: nginx-net
    external: true